export const ACCOUNT_CODES = {
  // Assets (1xxx)
  CASH: '1101',
  BANK: '1102',
  ACCOUNTS_RECEIVABLE: '1103',
  INVENTORY: '1104',
  PREPAID_EXPENSES: '1105',
  ACCRUED_REVENUE: '1106',
  FIXED_ASSETS: '1200',
  ACCUMULATED_DEPRECIATION: '1201',
  // Liabilities (2xxx)
  ACCOUNTS_PAYABLE: '2101',
  TAXES_PAYABLE: '2102',
  ACCRUED_EXPENSES: '2103',
  SHORT_TERM_LOANS: '2104',
  LONG_TERM_LOANS: '2200',
  // Equity (3xxx)
  OWNER_CAPITAL: '3100',
  RETAINED_EARNINGS: '3101',
  DRAWINGS: '3102',
  // Revenue (4xxx)
  SALES_REVENUE: '4100',
  PARTS_SALES: '4101',
  SERVICE_REVENUE: '4102',
  OTHER_REVENUE: '4200',
  // Expenses (5xxx)
  COGS: '5100',
  RENT_EXPENSE: '5201',
  SALARIES_EXPENSE: '5202',
  UTILITIES_EXPENSE: '5203',
  MARKETING_EXPENSE: '5204',
  OPERATING_EXPENSES: '5200',
  OTHER_EXPENSES: '5300',
  DEPRECIATION_EXPENSE: '5400',
} as const;

export type AccountCode = typeof ACCOUNT_CODES[keyof typeof ACCOUNT_CODES];

export const PAYMENT_METHODS = {
  CASH: 'cash',
  CARD: 'card',
  TRANSFER: 'transfer',
} as const;

export type PaymentMethod = typeof PAYMENT_METHODS[keyof typeof PAYMENT_METHODS];

export const JOURNAL_ENTRY_TYPES = {
  SALE: 'SALE',
  RETURN: 'RETURN',
  PURCHASE: 'PURCHASE',
  EXPENSE: 'EXPENSE',
  INCOME: 'INCOME',
  STOCK_ADJUSTMENT: 'STOCK_ADJUSTMENT',
  SUPPLIER_PAYMENT: 'SUPPLIER_PAYMENT',
} as const;

export type JournalEntryType = typeof JOURNAL_ENTRY_TYPES[keyof typeof JOURNAL_ENTRY_TYPES];
